- cassandra/src/main/java/org/apache/metamodel/cassandra/CassandraDataContext.java
- cassandra/src/test/java/org/apache/metamodel/cassandra/CassandraDataContextTest.java
proper message instead of NPE when keystore does not exist.
> METAMODEL-109: CassandraDataContext throws IllegalArgumentException with

- example-metamodel-integrationtest-configuration.properties
- hadoop/pom.xml
- hadoop/src/main/java/org/apache/metamodel/util/HdfsResource.java
- hadoop/src/test/java/org/apache/metamodel/util/HdfsResourceIntegrationTest.java
- hadoop/src/test/java/org/apache/metamodel/util/HdfsResourceTest.java
- hadoop/src/test/resources/log4j.xml
Trying to make the story more complete wrt. the HdfsResource testability. I made it use our normal integration test approach of having properties in ${user.home}/metamodel-integrationtest-configuration.properties that drive the setup of the test.
> Added HdfsResource integration test

- core/src/main/java/org/apache/metamodel/util/AbstractDirectoryInputStream.java
- core/src/main/java/org/apache/metamodel/util/FileResource.java
- core/src/test/java/org/apache/metamodel/util/FileResourceTest.java
- hadoop/src/main/java/org/apache/metamodel/util/HdfsResource.java
- hadoop/src/test/java/org/apache/metamodel/util/HdfsResourceIntegrationTest.java
This will allow FileResource and HdfsResource to use a folder as a complete resource. It will skip any subfolder and only use files in the folder. Before opening files, they will be sorted them alphabetically by name (actually it uses the natural ordering of the File/FileStatus object, but that is the path/url sorted alphabetically).
Fixes METAMODEL-163
> Adds ability to read folders to FileResource and HdfsResource

- CHANGES.md
- elasticsearch/src/main/java/org/apache/metamodel/elasticsearch/ElasticSearchDataContext.java
- elasticsearch/src/main/java/org/apache/metamodel/elasticsearch/ElasticSearchMetaDataParser.java
- elasticsearch/src/test/java/org/apache/metamodel/elasticsearch/ElasticSearchMetaDataParserTest.java
Previously the parser was (by accident I think) using the toString()
representation of that same map which made it very vulnerable towards
parsing issues.
Fixes METAMODEL-164
> METAMODEL-164: Fixed and refactored ES mapping parser to use real map.

- CHANGES.md
- core/src/main/java/org/apache/metamodel/util/AbstractResource.java
- core/src/main/java/org/apache/metamodel/util/ClasspathResource.java
- core/src/main/java/org/apache/metamodel/util/FileResource.java
- core/src/main/java/org/apache/metamodel/util/InMemoryResource.java
- core/src/main/java/org/apache/metamodel/util/Resource.java
- core/src/main/java/org/apache/metamodel/util/UrlResource.java
- csv/src/main/java/org/apache/metamodel/csv/CsvUpdateCallback.java
- hadoop/src/main/java/org/apache/metamodel/util/HdfsResource.java
- spring/src/main/java/org/apache/metamodel/spring/SpringResource.java
Fixes METAMODEL-173
See also previous PR #36 which had a different approach. This approach is in my opinion better since it tries to improve the way the CsvUpdateCallback remembers the output stream (in form of a Writer) and reuses it for each line it writes.
> CSV writing using Resource.write() and Resource.append()

- CHANGES.md
- jdbc/pom.xml
- jdbc/src/test/java/org/apache/metamodel/jdbc/DerbyTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/JdbcTestTemplates.java
METAMODEL-176: Fixed
Also added DataSet.close() to a few places where it was giving log
warnings during build/test
> Remove hadoop-common dependency in MetaModel-jdbc

- .travis.yml
- pom.xml
Note that the target of this PR is the new "5.x" branch.
This PR removes support for Java 7.
Fixes METAMODEL-222.
> METAMODEL-222: Removed Java 7 compatibility and build options

- core/src/main/java/org/apache/metamodel/AbstractUpdateCallback.java
- core/src/main/java/org/apache/metamodel/UpdateSummaryBuilder.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcBatchUpdateCallback.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcDeleteBuilder.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcDropTableBuilder.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcInsertBuilder.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcSimpleUpdateCallback.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcUpdateBuilder.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcUpdateCallback.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/JdbcTestTemplates.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/PostgresqlTest.java
Some more progress on METAMODEL-6. This adds support for the JDBC module to return number of inserts, updates, deletes and any generated keys. I chose the JDBC module because it is arguably the most complex. I imagine the reusing bits and pieces from here would be beneficial when implementing support in some of the other modules.
> METAMODEL-6: Added UpdateSummary building for JDBC module

- .travis.yml
- core/src/main/java/org/apache/metamodel/DataContext.java
- core/src/main/java/org/apache/metamodel/convert/TypeConverter.java
- core/src/main/java/org/apache/metamodel/data/DefaultRow.java
- core/src/main/java/org/apache/metamodel/query/OperatorType.java
- core/src/main/java/org/apache/metamodel/query/OperatorTypeImpl.java
- core/src/main/java/org/apache/metamodel/query/builder/SatisfiedQueryBuilder.java
- core/src/main/java/org/apache/metamodel/schema/Schema.java
- core/src/main/java/org/apache/metamodel/schema/Table.java
- core/src/main/java/org/apache/metamodel/util/FormatHelper.java
- core/src/main/java/org/apache/metamodel/util/SimpleTableDefParser.java
- core/src/test/java/org/apache/metamodel/query/parser/QueryParserTest.java
- elasticsearch/native/src/main/java/org/apache/metamodel/elasticsearch/nativeclient/ElasticSearchDataContext.java
- elasticsearch/rest/src/main/java/org/apache/metamodel/elasticsearch/rest/ElasticSearchRestDataContext.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/AbstractQueryRewriter.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/DB2QueryRewriter.java
- jdbc/src/test/java/org/apache/metamodel/dialects/DB2QueryRewriterTest.java
- mongodb/common/src/main/java/org/apache/metamodel/mongodb/common/MongoDBUtils.java
- mongodb/common/src/main/java/org/apache/metamodel/mongodb/common/MongoDbTableDef.java
- mongodb/mongo3/src/main/java/org/apache/metamodel/mongodb/mongo3/MongoDbDataContext.java
- pom.xml
- sugarcrm/pom.xml
- xml/src/main/java/org/apache/metamodel/xml/XmlDomDataContext.java
This PR fixes a bunch of errors in the javadoc comments of MetaModel. While running `mvn javadoc:javadoc` on a Java 8 runtime, then these bring build failures.
> Javadoc fixes

- pom.xml
- sugarcrm/pom.xml
With the 4.5.2 release I wanted to update the published javadocs but found that running ´mvn javadoc:aggregate` runs into problems because of the sugarcrm WSDL stubs that are generated and not 100% javadoc "correct". Normally we have an exclude rule for that in the sugarcrm module but since the ´aggregate´ goal runs on the parent module, it does not apply. So with this PR I want to change it back so that the exclusion is done in the parent POM.
I removed it from the sugarcrm module to avoid redundancy. Hope that is correct, but feedback welcome.
> Moved javadoc exclude to parent pom to fix 'mvn javadoc:aggregate'

- .gitignore
- elasticsearch/rest/src/main/java/org/apache/metamodel/elasticsearch/rest/JestElasticSearchUtils.java
- elasticsearch/rest/src/test/java/org/apache/metamodel/elasticsearch/rest/JestElasticSearchUtilsTest.java
This fixes METAMODEL-235 which was essentially about supporting null values and missing values in the REST API of ElasticSearch.
I also expanded the unittests a bit in general around the relevant utility class. It seemed that it didn't have a lot of corner cases covered so now I added a couple at least.
> METAMODEL-235: Fixed

- .gitignore
- elasticsearch/rest/src/main/java/org/apache/metamodel/elasticsearch/rest/JestElasticSearchUtils.java
- elasticsearch/rest/src/test/java/org/apache/metamodel/elasticsearch/rest/JestElasticSearchUtilsTest.java
Fixes METAMODEL-225 which is about nested JSON objects in ElasticSearch responses over the REST protocol.
I built this branch as a continuation of the METAMODEL-235 branch, so please first review the PR for that:
https://github.com/apache/metamodel/pull/94
> METAMODEL-225: Fixed

- CHANGES.md
- core/src/main/java/org/apache/metamodel/util/LegacyDeserializationObjectInputStream.java
This fix is implemented by further diving deep into the depths of OpenJDK. I'm not really fond of going down that route, but it seems to be the way to go if we really want to keep deserialization support.
Thanks to @LosD for the good hint on what had changed in OpenJDK by the way!
> METAMODEL-241: Fixed

- CHANGES.md
- core/src/main/java/org/apache/metamodel/MetaModelHelper.java
- core/src/main/java/org/apache/metamodel/data/AbstractDataSet.java
- core/src/main/java/org/apache/metamodel/data/UnionDataSet.java
- core/src/main/java/org/apache/metamodel/query/DefaultInvokableQuery.java
- core/src/main/java/org/apache/metamodel/query/InvokableQuery.java
- core/src/main/java/org/apache/metamodel/query/Query.java
- core/src/main/java/org/apache/metamodel/query/builder/SatisfiedQueryBuilder.java
- core/src/test/java/org/apache/metamodel/data/UnionDataSetTest.java
Here's my attempt at designing/solving METAMODEL-63.
Ideally we would support UNION also as part of our Query language. But that seems like a huge change and a much more low-hanging fruit would be to allow unions via a special `DataSet` implementation.
I also introduced a new interface, `InvokableQuery`. I've often had the need to pass around both DataContext and Query (because those two are needed in combination to produce the `DataSet`). The new interface allows passing these around in a more coherent and encapsulated way.
> METAMODEL-63: UnionDataSet

- core/src/main/java/org/apache/metamodel/AbstractDataContext.java
- core/src/main/java/org/apache/metamodel/BatchUpdateScript.java
- core/src/main/java/org/apache/metamodel/DataContext.java
- core/src/main/java/org/apache/metamodel/MetaModelHelper.java
- core/src/main/java/org/apache/metamodel/QueryPostprocessDataContext.java
- core/src/main/java/org/apache/metamodel/UpdateScript.java
- core/src/main/java/org/apache/metamodel/UpdateableDataContext.java
- core/src/main/java/org/apache/metamodel/annotations/InterfaceStability.java
- core/src/main/java/org/apache/metamodel/data/AbstractDataSet.java
- core/src/main/java/org/apache/metamodel/query/Query.java
- core/src/main/java/org/apache/metamodel/schema/Column.java
- core/src/main/java/org/apache/metamodel/schema/ColumnType.java
- core/src/main/java/org/apache/metamodel/schema/Relationship.java
- core/src/main/java/org/apache/metamodel/schema/Schema.java
- core/src/main/java/org/apache/metamodel/schema/Table.java
- example-metamodel-integrationtest-configuration.properties
- kafka/pom.xml
- kafka/src/main/java/org/apache/metamodel/kafka/ConsumerAndProducerFactory.java
- kafka/src/main/java/org/apache/metamodel/kafka/ConsumerFactory.java
- kafka/src/main/java/org/apache/metamodel/kafka/KafkaConsumerAndProducerFactory.java
- kafka/src/main/java/org/apache/metamodel/kafka/KafkaConsumerFactory.java
- kafka/src/main/java/org/apache/metamodel/kafka/KafkaDataContext.java
- kafka/src/main/java/org/apache/metamodel/kafka/KafkaDataSet.java
- kafka/src/main/java/org/apache/metamodel/kafka/KafkaInsertBuilder.java
- kafka/src/main/java/org/apache/metamodel/kafka/KafkaUpdateCallback.java
- kafka/src/test/java/org/apache/metamodel/kafka/KafkaDataContextIntegrationTest.java
- kafka/src/test/java/org/apache/metamodel/kafka/KafkaDataContextTest.java
- kafka/src/test/java/org/apache/metamodel/kafka/KafkaTestServer.java
- pom.xml
- travis-metamodel-integrationtest-configuration.properties
Hi all,
I've been playing around with this idea for a while and decided to try it out ... I'm curious what you think!
This is a new MM module which allows you to query Apache Kafka. By "query" I mean: Each topic is represented as a table. And fields in here include `partition`, `offset`, `key`, `value` and `timestamp`.
When querying, the MM module creates a new unique Kafka consumer. This works, but I have one worry, which I don't really know how to mitigate: Consumers are registered in Kafka and cannot be deleted without pulling some tricks that go all the way into Zookeeper. This worries me because then every query fired will leave behind a new consumer ID in Zookeeper. If you use this module a lot then, then it becomes a lot of garbage.
Except for the issue described above, I think …
> A new module for Apache Kafka "querying" using MetaModel

- core/src/main/java/org/apache/metamodel/data/RowPublisherDataSet.java
- core/src/main/java/org/apache/metamodel/schema/MutableRelationship.java
- csv/src/main/java/org/apache/metamodel/csv/CsvDataSet.java
- elasticsearch/common/src/main/java/org/apache/metamodel/elasticsearch/AbstractElasticSearchDataSet.java
- elasticsearch/native/pom.xml
- fixedwidth/src/main/java/org/apache/metamodel/fixedwidth/FixedWidthDataSet.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcCompiledQuery.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcDataSet.java
- mongodb/mongo2/src/main/java/org/apache/metamodel/mongodb/mongo2/MongoDbDataSet.java
- mongodb/mongo3/src/main/java/org/apache/metamodel/mongodb/mongo3/MongoDbDataSet.java
- openoffice/src/main/java/org/apache/metamodel/openoffice/OpenOfficeDataContext.java
- pom.xml
Since JDK9 the `Object.finalize()` method has been marked as `@Deprecated`. In this PR I removed references to `Objects`s `finalize` method, and tried to get rid of our own `finalize` method where possible without introducing potential issues.
Oh and there was a small junit dependency inconsistency.
I guess I just decided to weed out a couple of warnings really :-)
> Don't use Object.finalize()

- core/src/main/java/org/apache/metamodel/util/NumberComparator.java
- core/src/test/java/org/apache/metamodel/util/NumberComparatorTest.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/OracleQueryRewriter.java
Oracle has "TIMESTAMP WITH LOCAL_TIME_ZONE" and TIMESTAMP WITH TIME_ZONE" column type, which  MetaModel doesn't support now.
> add support for Oracle "TIMESTAMP WITH (LOCAL_)TIME_ZONE" column type.

- jdbc/pom.xml
This PR updates Hive from version 1.2.1 to 2.3.2, which is the latest version.
> Update Hive version

- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcCreateTableBuilder.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/DefaultQueryRewriter.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/HiveQueryRewriter.java
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/IQueryRewriter.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/HiveIntegrationTest.java
Hive doesn't support primary keys. This PR makes sure, that when a column is defined as a primary key, then  this is ignored in the create table statement.
> METAMODEL-1194 Don't support primary keys with Hive

- pom.xml
I believe this fixes METAMODEL-1193 since the new apache parent-pom contains this plugin configuration:
```
<plugin>
<groupId>net.nicoulaj.maven.plugins</groupId>
<artifactId>checksum-maven-plugin</artifactId>
<version>1.7</version>
...
<configuration>
<algorithms>
<algorithm>SHA-512</algorithm>
</algorithms>
```
> METAMODEL-1193: Upgraded parent-pom to enable sha-512 signing.

- core/src/main/java/org/apache/metamodel/factory/DataContextFactoryRegistryImpl.java
In the Membrane sub-project it will become relevant (for METAMODEL-1159)
to be able to make copies of the "default" registry, but with additional
tenant-specific factories, too. So this change makes it easier for
Membrane to copy a DataContextFactoryRegistry.
> Added more flexible ways to create DataContextFactoryRegistry.

- core/src/main/java/org/apache/metamodel/MetaModelHelper.java
- pojo/src/test/java/org/apache/metamodel/pojo/PojoDataContextTest.java
- pojo/src/test/java/org/apache/metamodel/pojo/Role.java
- pojo/src/test/java/org/apache/metamodel/pojo/User.java
Fixes MM-1211.
When determining the Carthesian product for a query over multiple tables make sure that when determining which FilterItems are applicable for the query the SelectItems for compound FilterItems are also taken into consideration by recursively inspecting the children of the compound FilterItems.
> Recursively get SelectItems from FilterItems when using nested loop join

- CHANGES.md
- jdbc/src/main/java/org/apache/metamodel/jdbc/JdbcDropTableBuilder.java
Fixes: [METAMODEL-1217 - Drop table doesn't work for views with JDBC Tables](https://issues.apache.org/jira/browse/METAMODEL-1217)
> METAMODEL-1217 - Fixes dropping JDBC Tables with view as TableType

- CHANGES.md
- core/src/main/java/org/apache/metamodel/schema/AbstractSchema.java
Closes: [METAMODEL-1218 - Can't compare schema's without a name](https://issues.apache.org/jira/browse/METAMODEL-1218)
> MM-1218 Compare schemas with name null

- pom.xml
For some reason having the -Xdoclint:none in the additionalParam tag no longer works for me (probably because of my java version) for ignoring javadoc problems, so I'm changing this to using the doclint tag.
The normal travis build for MetaModel doesn't fail on this, so I think it is introduced by newer java version, for me it fails both with openjdk 8.0.212.04 and Oracle jdk 1.8.0_211. I haven't installed an older version of java 8 to see if the old implementation works there, but I think it does, because travis builds successfull. This change however seems to work on all java versions. It was inspired by https://stackoverflow.com/questions/52547306/maven-javadoc-plugin-not-accepting-additionalparam-xdoclintnone-additionalpa.
> Change doclint suppression in javadoc pluging

- CHANGES.md
- excel/src/main/java/org/apache/metamodel/excel/ExcelUtils.java
- excel/src/test/java/org/apache/metamodel/excel/ExcelDataContextTest.java
Closes: [METAMODEL-82](https://issues.apache.org/jira/browse/METAMODEL-82)
I found a bug in my implementation [MM-PR234](https://github.com/apache/metamodel/pull/234): When Integer values were in a Double column, then these values were set to NULL when querying the result.
> METAMODEL-82 - Fix integers in double columns

- jdbc/pom.xml
The actual code using guava class CharMatcher was removed in PR https://github.com/apache/metamodel/pull/195 (METAMODEL-1205)
But the guava dependency is still part of POM.
Since the dependency is no more required removing the same
> METAMODEL-1201 Remove guava dependency in package jdbc

- CHANGES.md
- core/src/main/java/org/apache/metamodel/query/FromItem.java
- jdbc/pom.xml
- jdbc/src/main/java/org/apache/metamodel/jdbc/dialects/PostgresqlQueryRewriter.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/dialects/PostgresqlQueryRewriterTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/PostgresqlTest.java
Reproduced the issue in METAMODEL-1224 and tried upgrading the driver. This fixed the issue it seems, so here's an updated test since a few error messages have been updated from the driver's side as well.
Also, with the old driver the underlying issue seems to be that the schema name comes out as blank. I'm not sure why, but probably just a driver-and-database version conflict. I updated the code to not generate queries with blank schema names, but in those cases follow the routes of not prefixing tables with schema names.
> METAMODEL-1224: Fixed PostgreSQL compatibility (upgrading driver+tests)

- CHANGES.md
- elasticsearch/common/src/main/java/org/apache/metamodel/elasticsearch/common/ElasticSearchMetaDataParser.java
- elasticsearch/rest/src/test/java/org/apache/metamodel/elasticsearch/rest/ElasticSearchRestNestedDataIT.java
Fixes METAMODEL-1227.
In case an Elasticsearch document contains nested objects, these should be designated the `ColumnType.MAP`,  because they're resolved to `Map` objects, not to `String` objects.
> Better handling of nested objects in Elasticsearch data

- CHANGES.md
- elasticsearch/common/src/main/java/org/apache/metamodel/elasticsearch/common/ElasticSearchUtils.java
- elasticsearch/rest/src/test/java/org/apache/metamodel/elasticsearch/rest/ElasticSearchRestNestedDataIT.java
MetaModel is unable to work with a document indexed by Elasticsearch which contains dots in its field names. Note that this is actually caused by Elasticsearch, because the mapping returned for such a document by Elasticsearch doesn't match the source returned by Elasticsearch when getting the source of a search hit. (see https://github.com/elastic/elasticsearch-hadoop/issues/853 and related issues for more info on this).
Note that the branch for this PR is branch off of the branch for https://github.com/apache/metamodel/pull/242, because it extends the Integration Test which is introduced in that PR.
> Workaround for fieldnames with dots in elasticsearch

- CHANGES.md
- fixedwidth/src/main/java/org/apache/metamodel/fixedwidth/FixedWidthDataContext.java
- fixedwidth/src/test/java/org/apache/metamodel/fixedwidth/FixedWidthDataContextTest.java
Fixes https://issues.apache.org/jira/browse/METAMODEL-1229. 
EbcdicReader in FixedWidthDataContext required BufferedInputStream, now other input streams are also supported (new BufferedInputStream(originalInputStream) is created). 
This enables using a URL (UrlResource) for a path in FixedWidth datastore.
> MM-1229: FixedWidth works with UrlResource/HttpInputStream.

- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/AbstractJdbIntegrationTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/DB2Test.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/FirebirdTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/HiveIntegrationTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/MysqlTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/OracleTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/PostgresqlTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/SQLServerJtdsDriverTest.java
- jdbc/src/test/java/org/apache/metamodel/jdbc/integrationtests/SQLServerMicrosoftDriverTest.java
Fixes the following error when running the JDBC integration test:
```
ERROR 17:38:56 JdbcUtils - Could not execute batch: INSERT INTO "public"."my_table" ("person name",age) VALUES ('John Doe','42'): Batch entry 0 INSERT INTO "public"."my_table" ("person name",age) VALUES ('John Doe','42') was aborted: ERROR: column
"age" is of type integer but expression is of type character varying
```
> METAMODEL-1231 PostgreSQL integration test errors

- CHANGES.md
- elasticsearch/common/src/main/java/org/apache/metamodel/elasticsearch/common/ElasticSearchUtils.java
- elasticsearch/common/src/test/java/org/apache/metamodel/elasticsearch/common/ElasticSearchUtilsTest.java
Fixes https://issues.apache.org/jira/browse/METAMODEL-1233 
Elasticsearch used a 'term' query for `WHERE text_based_column = 'text-value'` situations. This PR introduces a new condition covering this scenario and creating a 'match' query instead.
> METAMODEL-1233: Elasticsearch uses 'match' query for text based columns conditions in WHERE clause

- elasticsearch/common/src/main/java/org/apache/metamodel/elasticsearch/common/ElasticSearchUtils.java
- excel/src/test/java/org/apache/metamodel/excel/ExcelDataContextTest.java
Fixes https://issues.apache.org/jira/browse/METAMODEL-1232.
- I refactored the `ExcelDataContextTest` from using JUnit 3 to JUnit 4, so it can use the ` TemporaryFolder` rule for copying files when using them it tests. It seems this works better than when copying them to the target folder.
- I refactored the logic used by `ElasticSearchUtils#createRow(...)`  for creating a row based on a MAP column type. It uses `computeIfAbsent` to put a `HashMap`  in a `Map`, but then within the method that created that `HashMap`, it would already add the created `HashMap` to the `Map`, which is something that should be handled by the `computeIfAbsent` itself, which apparently can lead to `ConcurrentModificationExpection`s being thrown.
> Build on Travis fails most of the time

- elasticsearch/common/src/main/java/org/apache/metamodel/elasticsearch/common/ElasticSearchUtils.java
- elasticsearch/common/src/test/java/org/apache/metamodel/elasticsearch/common/ElasticSearchUtilsTest.java
- elasticsearch/rest/src/test/java/org/apache/metamodel/elasticsearch/rest/ElasticSearchRestDataContextIT.java
Fixes https://issues.apache.org/jira/browse/METAMODEL-1236. 
This PR fixes following operations in Elasticsearch: 
- new FilterItem(new SelectItem(column), OperatorType.EQUALS_TO, null)
- new FilterItem(new SelectItem(column), OperatorType.DIFFERENT_FROM, null)
- new FilterItem(new SelectItem(column), OperatorType.EQUALS_TO, "")
- new FilterItem(new SelectItem(column), OperatorType.DIFFERENT_FROM, "")
> Elasticsearch: not/empty and is/not null

- CHANGES.md
- core/src/main/java/org/apache/metamodel/AbstractDataContext.java
Fixes https://issues.apache.org/jira/browse/METAMODEL-1235. 
Problem in AbstractDataContext.searchColumn when schema name and column name are equal was fixed.
> MM-1235: AbstractDataContext.searchColumn was fixed for situation when schema and column are equal strings
